services:
  snatcher:
    image: ghcr.io/mhmdxsadk/snatcher:latest
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    stop_grace_period: 50s
    ports:
      - "127.0.0.1:8080:8080/tcp"
    environment:
      COBALT_API: "http://your-cobalt-host:9000"
      SNATCHER_API_KEY: "GENERATE_ME" # Generate with: openssl rand -hex 32
