services:
  snatcher:
    build: .
    image: ghcr.io/mhmdxsadk/snatcher:latest
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp:mode=1777,size=2g
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    stop_grace_period: 50s
    ports:
      - "127.0.0.1:8080:8080/tcp"
    environment:
      SNATCHER_API_KEY: "GENERATE_ME" # Generate with: openssl rand -hex 32
